---
- name: Copy Axel RPM
  copy: src=axel/axel-2.4-1.el7.centos.x86_64.rpm dest={{ work_dir }}/axel-2.4-1.el7.centos.x86_64.rpm

- name: Install Axel
  yum: name={{ work_dir }}/axel-2.4-1.el7.centos.x86_64.rpm state=present
